### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by hoyanxun** [google-developer-training/android-basics-kotlin-affirmations-app-solution#11]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-lists?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#4

**In which task and step of the codelab can this issue be found?**
At the "5. Put it all together" section

**Describe the problem**
At the detailed explanation of the output of the code, the subclass of its parent class(Item)"Noodles" is called "Noodle"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by amindadgar** [comment]
If I understand your question right my answer is
Using super keyword in an override function will call the codes in parent , and if you use additional codes in it you can do more but if you do not use super keyword in override function you will ignore the parent codes ( function in parent class ).

example:
if you have this class
```
open class Property(val name:String) {
	open fun printName(){
        println(name)
    }
}
```
and you inherit this two classes:
```
class newProperty(val myName: String): Property(myName){
    override fun printName(){
        super.printName()
        println("this is my overriden function with super keyword")
    }
}

class newProperty2(val myName: String): Property(myName){
    override fun printName(){
        // here we didn't call the supper keyword
        println("this is my overriden function without super keyword!")
    }
}

```
And if you write this code as your main function 
```
fun main(){
   val n = newProperty("Nilson")
   n.printName()
}
```
**Result will be:**
  _Nilson
  this is my overriden function with super keyword_

And if you use this code as your main function:
```
fun main(){
   val n = newProperty2("Nilson")
   n.printName()
}
```
**Result will be:**
  _this is my overriden function without super keyword!_

Also I've attached some links for you to get a better understanding of inheritance in Kotlin  

1. https://www.journaldev.com/19705/kotlin-inheritance#:~:text=All%20classes%20in%20Kotlin%20have,because%20of%20famous%20diamond%20problem.
2. https://stackoverflow.com/a/46400277

If you had any further questions I am here to help you 🙂

**Comment by jtavva** [comment]
@hoyanxun 
Thank you so much for reporting this issue. This is fixed and will be published soon.
