### ISSUE TITLE
Android Basics: display-list-cards

### ISSUE THREAD

**Issue by tango4567** [google-developer-training/android-basics-kotlin-affirmations-app-solution#2]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-display-list-cards&hl=en#2

**In which task and step of the codelab can this issue be found?**
Step 5. Copy the following into the new themes.xml file (in the values-night directory).

**Describe the problem**
**@color/status_bar_night** 
Missing color item in **colors**.xml

**Versions**
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-48-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, com.google.services.firebase, com.intellij.marketplace, com.thoughtworks.gauge, io.flutter, org.intellij.plugins.markdown

**Additional information**
I know at this stage it can be ignored. But it's better to add in codelab.

**Comment by jtavva** [comment]
Thank you for reaching out to us.
Actual issue was in the code snippet for `themes.xml `file (in the `values-night` directory). 

Correct code snippet: 
`<item name="android:statusBarColor" tools:targetApi="l">@color/colorPrimaryVariant</item>`

Color used for `android:statusBarColor` is `colorPrimaryVariant` not `status_bar_night`. 

Solution code for your reference: 
https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/blob/main/app/src/main/res/values-night/themes.xml

Thank you so much for reporting this issue. This is fixed and will be published soon.
Hope this helps!
