### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by rustymetal213** [google-developer-training/android-basics-kotlin-affirmations-app-solution#95]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#10

**In which task and step of the Codelab can this issue be found?*

11. Solution Code 
solution: test_solution

**Describe the problem**

looking for solution for "test list and adapters" but when I click on the github link provided it sends me to a version prior implementation of test. it prompts me to search for a module named test_solution that i cant find anywhere 

**Steps to reproduce?**
1. Go to...Training>Android Basics in Kotlin>Layouts>Scrollable Lists>Tests And Adapters>11. Solution code 

2. Click on...https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution

3. See error... test_solution nowhere to be found 

**Versions**
_What version of Android Studio are you using?_

Android studio Artic fox 2020.3.1 patch 4 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by rock-chock** [comment]
@rustymetal213  Same issue for me! 

I wanted to check my solution to the actual. 

Found the [test_solution] branch in this project that is 2 commits ahead of [main] if it helps.

Branch:
https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/tree/test_solution

Changed files with the solution: 
https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/commit/47e95687a0acbdf7da6ca937abd05e434fc876c3


Also, I find the part [Test Lists and Adapters. Part 7. Test the RecyclerView](https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6) pretty confusing for beginners like me because it doesn't provide sufficient examples that I could check against.
